import { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-steps',
    title: 'First Steps',
    titleKey: 'achievementTitle.firstSteps',
    description: 'Complete your first course',
    descriptionKey: 'achievementDesc.firstSteps',
    tier: 'bronze',
    category: 'course',
    icon: 'GraduationCap',
    requirement: 1,
  },
  {
    id: 'learning-specialist-i',
    title: 'Learning Specialist I',
    titleKey: 'achievementTitle.learningSpecialistI',
    description: 'Complete 5 courses',
    descriptionKey: 'achievementDesc.learningSpecialistI',
    tier: 'silver',
    category: 'course',
    icon: 'BookOpen',
    requirement: 5,
  },
  {
    id: 'learning-specialist-ii',
    title: 'Learning Specialist II',
    titleKey: 'achievementTitle.learningSpecialistII',
    description: 'Complete 10 courses',
    descriptionKey: 'achievementDesc.learningSpecialistII',
    tier: 'gold',
    category: 'course',
    icon: 'BookBookmark',
    requirement: 10,
  },
  {
    id: 'learning-specialist-iii',
    title: 'Learning Specialist III',
    titleKey: 'achievementTitle.learningSpecialistIII',
    description: 'Complete 15 courses',
    descriptionKey: 'achievementDesc.learningSpecialistIII',
    tier: 'platinum',
    category: 'course',
    icon: 'Trophy',
    requirement: 15,
  },
  {
    id: 'learning-master',
    title: 'Learning Master',
    titleKey: 'achievementTitle.learningMaster',
    description: 'Complete 25 courses',
    descriptionKey: 'achievementDesc.learningMaster',
    tier: 'platinum',
    category: 'course',
    icon: 'Crown',
    requirement: 25,
  },
  {
    id: 'learning-legend',
    title: 'Learning Legend',
    titleKey: 'achievementTitle.learningLegend',
    description: 'Complete 50 courses',
    descriptionKey: 'achievementDesc.learningLegend',
    tier: 'platinum',
    category: 'course',
    icon: 'Star',
    requirement: 50,
  },
  {
    id: 'quick-study',
    title: 'Quick Study',
    titleKey: 'achievementTitle.quickStudy',
    description: 'Complete 10 modules in a single session',
    descriptionKey: 'achievementDesc.quickStudy',
    tier: 'silver',
    category: 'speed',
    icon: 'Lightning',
    requirement: 10,
  },
  {
    id: 'perfect-score',
    title: 'Perfect Score',
    titleKey: 'achievementTitle.perfectScore',
    description: 'Achieve 100% on an assessment',
    descriptionKey: 'achievementDesc.perfectScore',
    tier: 'gold',
    category: 'assessment',
    icon: 'Star',
    requirement: 1,
  },
  {
    id: 'assessment-specialist-i',
    title: 'Assessment Specialist I',
    titleKey: 'achievementTitle.assessmentSpecialistI',
    description: 'Pass 5 assessments with 90% or higher',
    descriptionKey: 'achievementDesc.assessmentSpecialistI',
    tier: 'silver',
    category: 'assessment',
    icon: 'Medal',
    requirement: 5,
  },
  {
    id: 'assessment-specialist-ii',
    title: 'Assessment Specialist II',
    titleKey: 'achievementTitle.assessmentSpecialistII',
    description: 'Pass 10 assessments with 90% or higher',
    descriptionKey: 'achievementDesc.assessmentSpecialistII',
    tier: 'gold',
    category: 'assessment',
    icon: 'Medal',
    requirement: 10,
  },
  {
    id: 'assessment-specialist-iii',
    title: 'Assessment Specialist III',
    titleKey: 'achievementTitle.assessmentSpecialistIII',
    description: 'Pass 25 assessments with 90% or higher',
    descriptionKey: 'achievementDesc.assessmentSpecialistIII',
    tier: 'platinum',
    category: 'assessment',
    icon: 'Medal',
    requirement: 25,
  },
  {
    id: 'week-warrior',
    title: '7-Day Study Streak',
    titleKey: 'achievementTitle.sevenDayStreak',
    description: 'Study for 7 days in a row',
    descriptionKey: 'achievementDesc.sevenDayStreak',
    tier: 'silver',
    category: 'streak',
    icon: 'Fire',
    requirement: 7,
  },
  {
    id: 'dedication',
    title: '30-Day Study Streak',
    titleKey: 'achievementTitle.thirtyDayStreak',
    description: 'Study for 30 days in a row',
    descriptionKey: 'achievementDesc.thirtyDayStreak',
    tier: 'gold',
    category: 'streak',
    icon: 'Flame',
    requirement: 30,
  },
  {
    id: 'streak-specialist-i',
    title: 'Streak Specialist I',
    titleKey: 'achievementTitle.streakSpecialistI',
    description: 'Study for 60 days in a row',
    descriptionKey: 'achievementDesc.streakSpecialistI',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 60,
  },
  {
    id: 'streak-specialist-ii',
    title: 'Streak Specialist II',
    titleKey: 'achievementTitle.streakSpecialistII',
    description: 'Study for 90 days in a row',
    descriptionKey: 'achievementDesc.streakSpecialistII',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 90,
  },
  {
    id: 'unstoppable',
    title: 'Unstoppable',
    titleKey: 'achievementTitle.unstoppable',
    description: 'Study for 180 days in a row',
    descriptionKey: 'achievementDesc.unstoppable',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 180,
  },
  {
    id: 'module-specialist-i',
    title: 'Module Specialist I',
    titleKey: 'achievementTitle.moduleSpecialistI',
    description: 'Complete 25 learning modules',
    descriptionKey: 'achievementDesc.moduleSpecialistI',
    tier: 'bronze',
    category: 'milestone',
    icon: 'CheckCircle',
    requirement: 25,
  },
  {
    id: 'module-specialist-ii',
    title: 'Module Specialist II',
    titleKey: 'achievementTitle.moduleSpecialistII',
    description: 'Complete 50 learning modules',
    descriptionKey: 'achievementDesc.moduleSpecialistII',
    tier: 'silver',
    category: 'milestone',
    icon: 'CheckCircle',
    requirement: 50,
  },
  {
    id: 'module-specialist-iii',
    title: 'Module Specialist III',
    titleKey: 'achievementTitle.moduleSpecialistIII',
    description: 'Complete 100 learning modules',
    descriptionKey: 'achievementDesc.moduleSpecialistIII',
    tier: 'gold',
    category: 'milestone',
    icon: 'Target',
    requirement: 100,
  },
  {
    id: 'module-master',
    title: 'Module Master',
    titleKey: 'achievementTitle.moduleMaster',
    description: 'Complete 250 learning modules',
    descriptionKey: 'achievementDesc.moduleMaster',
    tier: 'platinum',
    category: 'milestone',
    icon: 'Rocket',
    requirement: 250,
  },
  {
    id: 'module-legend',
    title: 'Module Legend',
    titleKey: 'achievementTitle.moduleLegend',
    description: 'Complete 500 learning modules',
    descriptionKey: 'achievementDesc.moduleLegend',
    tier: 'platinum',
    category: 'milestone',
    icon: 'Trophy',
    requirement: 500,
  },
  {
    id: 'first-try',
    title: 'First Try Success',
    titleKey: 'achievementTitle.firstTrySuccess',
    description: 'Pass an assessment on the first attempt',
    descriptionKey: 'achievementDesc.firstTrySuccess',
    tier: 'bronze',
    category: 'assessment',
    icon: 'Lightbulb',
    requirement: 1,
  },
  {
    id: 'speed-runner',
    title: 'Speed Runner',
    titleKey: 'achievementTitle.speedRunner',
    description: 'Complete a course in under 1 hour',
    descriptionKey: 'achievementDesc.speedRunner',
    tier: 'gold',
    category: 'speed',
    icon: 'Timer',
    requirement: 1,
    hidden: true,
  },
  {
    id: 'quarterly-engagement',
    title: 'Quarterly Engagement Badge',
    titleKey: 'achievementTitle.quarterlyEngagement',
    description: 'Complete at least 10 activities in a quarter',
    descriptionKey: 'achievementDesc.quarterlyEngagement',
    tier: 'silver',
    category: 'milestone',
    icon: 'Calendar',
    requirement: 1,
    hidden: true,
  },
  {
    id: 'team-up',
    title: 'Team Up',
    titleKey: 'achievementTitle.teamUp',
    description: 'Complete your first mission with guidance from your Mentor',
    descriptionKey: 'achievementDesc.teamUp',
    tier: 'bronze',
    category: 'course',
    icon: 'UsersFour',
    requirement: 1,
  },
]

export const TIER_COLORS = {
  bronze: {
    bg: 'bg-amber-700',
    text: 'text-amber-700',
    border: 'border-amber-700',
    gradient: 'from-amber-600 to-amber-800',
  },
  silver: {
    bg: 'bg-slate-400',
    text: 'text-slate-600',
    border: 'border-slate-400',
    gradient: 'from-slate-300 to-slate-500',
  },
  gold: {
    bg: 'bg-yellow-500',
    text: 'text-yellow-600',
    border: 'border-yellow-500',
    gradient: 'from-yellow-400 to-yellow-600',
  },
  platinum: {
    bg: 'bg-cyan-400',
    text: 'text-cyan-500',
    border: 'border-cyan-400',
    gradient: 'from-cyan-300 to-cyan-500',
  },
}

export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id)
}

export function getTierLabel(tier: Achievement['tier']): string {
  return tier.charAt(0).toUpperCase() + tier.slice(1)
}
