import { Achievement } from './types'

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-steps',
    title: 'First Steps',
    description: 'Complete your first course',
    tier: 'bronze',
    category: 'course',
    icon: 'GraduationCap',
    requirement: 1,
  },
  {
    id: 'learning-specialist-i',
    title: 'Learning Specialist I',
    description: 'Complete 5 courses',
    tier: 'silver',
    category: 'course',
    icon: 'BookOpen',
    requirement: 5,
  },
  {
    id: 'learning-specialist-ii',
    title: 'Learning Specialist II',
    description: 'Complete 10 courses',
    tier: 'gold',
    category: 'course',
    icon: 'BookBookmark',
    requirement: 10,
  },
  {
    id: 'learning-specialist-iii',
    title: 'Learning Specialist III',
    description: 'Complete 15 courses',
    tier: 'platinum',
    category: 'course',
    icon: 'Trophy',
    requirement: 15,
  },
  {
    id: 'learning-master',
    title: 'Learning Master',
    description: 'Complete 25 courses',
    tier: 'platinum',
    category: 'course',
    icon: 'Crown',
    requirement: 25,
  },
  {
    id: 'learning-legend',
    title: 'Learning Legend',
    description: 'Complete 50 courses',
    tier: 'platinum',
    category: 'course',
    icon: 'Star',
    requirement: 50,
  },
  {
    id: 'quick-study',
    title: 'Quick Study',
    description: 'Complete 10 modules in a single session',
    tier: 'silver',
    category: 'speed',
    icon: 'Lightning',
    requirement: 10,
  },
  {
    id: 'perfect-score',
    title: 'Perfect Score',
    description: 'Achieve 100% on an assessment',
    tier: 'gold',
    category: 'assessment',
    icon: 'Star',
    requirement: 1,
  },
  {
    id: 'assessment-specialist-i',
    title: 'Assessment Specialist I',
    description: 'Pass 5 assessments with 90% or higher',
    tier: 'silver',
    category: 'assessment',
    icon: 'Medal',
    requirement: 5,
  },
  {
    id: 'assessment-specialist-ii',
    title: 'Assessment Specialist II',
    description: 'Pass 10 assessments with 90% or higher',
    tier: 'gold',
    category: 'assessment',
    icon: 'Medal',
    requirement: 10,
  },
  {
    id: 'assessment-specialist-iii',
    title: 'Assessment Specialist III',
    description: 'Pass 25 assessments with 90% or higher',
    tier: 'platinum',
    category: 'assessment',
    icon: 'Medal',
    requirement: 25,
  },
  {
    id: 'week-warrior',
    title: '7-Day Study Streak',
    description: 'Study for 7 days in a row',
    tier: 'silver',
    category: 'streak',
    icon: 'Fire',
    requirement: 7,
  },
  {
    id: 'dedication',
    title: '30-Day Study Streak',
    description: 'Study for 30 days in a row',
    tier: 'gold',
    category: 'streak',
    icon: 'Flame',
    requirement: 30,
  },
  {
    id: 'streak-specialist-i',
    title: 'Streak Specialist I',
    description: 'Study for 60 days in a row',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 60,
  },
  {
    id: 'streak-specialist-ii',
    title: 'Streak Specialist II',
    description: 'Study for 90 days in a row',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 90,
  },
  {
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Study for 180 days in a row',
    tier: 'platinum',
    category: 'streak',
    icon: 'FireSimple',
    requirement: 180,
  },
  {
    id: 'module-specialist-i',
    title: 'Module Specialist I',
    description: 'Complete 25 learning modules',
    tier: 'bronze',
    category: 'milestone',
    icon: 'CheckCircle',
    requirement: 25,
  },
  {
    id: 'module-specialist-ii',
    title: 'Module Specialist II',
    description: 'Complete 50 learning modules',
    tier: 'silver',
    category: 'milestone',
    icon: 'CheckCircle',
    requirement: 50,
  },
  {
    id: 'module-specialist-iii',
    title: 'Module Specialist III',
    description: 'Complete 100 learning modules',
    tier: 'gold',
    category: 'milestone',
    icon: 'Target',
    requirement: 100,
  },
  {
    id: 'module-master',
    title: 'Module Master',
    description: 'Complete 250 learning modules',
    tier: 'platinum',
    category: 'milestone',
    icon: 'Rocket',
    requirement: 250,
  },
  {
    id: 'module-legend',
    title: 'Module Legend',
    description: 'Complete 500 learning modules',
    tier: 'platinum',
    category: 'milestone',
    icon: 'Trophy',
    requirement: 500,
  },
  {
    id: 'first-try',
    title: 'First Try Success',
    description: 'Pass an assessment on the first attempt',
    tier: 'bronze',
    category: 'assessment',
    icon: 'Lightbulb',
    requirement: 1,
  },
  {
    id: 'speed-runner',
    title: 'Speed Runner',
    description: 'Complete a course in under 1 hour',
    tier: 'gold',
    category: 'speed',
    icon: 'Timer',
    requirement: 1,
    hidden: true,
  },
  {
    id: 'quarterly-engagement',
    title: 'Quarterly Engagement Badge',
    description: 'Complete at least 10 activities in a quarter',
    tier: 'silver',
    category: 'milestone',
    icon: 'Calendar',
    requirement: 1,
    hidden: true,
  },
]

export const TIER_COLORS = {
  bronze: {
    bg: 'bg-amber-700',
    text: 'text-amber-700',
    border: 'border-amber-700',
    gradient: 'from-amber-600 to-amber-800',
  },
  silver: {
    bg: 'bg-slate-400',
    text: 'text-slate-600',
    border: 'border-slate-400',
    gradient: 'from-slate-300 to-slate-500',
  },
  gold: {
    bg: 'bg-yellow-500',
    text: 'text-yellow-600',
    border: 'border-yellow-500',
    gradient: 'from-yellow-400 to-yellow-600',
  },
  platinum: {
    bg: 'bg-cyan-400',
    text: 'text-cyan-500',
    border: 'border-cyan-400',
    gradient: 'from-cyan-300 to-cyan-500',
  },
}

export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id)
}

export function getTierLabel(tier: Achievement['tier']): string {
  return tier.charAt(0).toUpperCase() + tier.slice(1)
}
